# Generated by Django 5.1.4 on 2026-09-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversionjob',
            new_name='pdf_tools_c_tool_sl_2a9b8b_idx',
            old_name='pdf_tools_c_tool_sl_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='conversionjob',
            new_name='pdf_tools_c_status_e328da_idx',
            old_name='pdf_tools_c_status_4d5e6f_idx',
        ),
    ]
